# Generated by Django 4.1.7 on 2023-04-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_candosomething_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('trained', 'Trained'), ('worker', 'Student Worker')]},
        ),
    ]
