# Generated by Django 4.1.7 on 2023-04-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanDoSomething',
            new_name='UserPermsissions',
        ),
    ]
