# Generated by Django 4.1.6 on 2023-04-12 22:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(choices=[('Desktop Computers', 'Desktop Computers'), ('Soldering Stations', 'Soldering Stations'), ('Electronics Station', 'Electronics Stations'), ('Lasers', 'Lasers'), ('3D Printers', '3D Printers'), ('CNC Machine', 'CNC Machine'), ('Vacuum Former', 'Vacuum Former'), ('Vinyl Cutter', 'Vinyl Cutter'), ('Heat Press', 'Heat Press'), ('Assembly Stations', 'Assembly Stations'), ('Photo Studio', 'Photo Studio'), ('Format Printer', 'Format Printer')], default='Desktop Computers', max_length=50)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('8 AM', '8 AM'), ('10 AM', '10 AM'), ('12 AM', '12 AM'), ('2 PM', '2 PM'), ('4 PM', '4 PM'), ('6 PM', '6 PM'), ('8 PM', '8 PM')], default='2 PM', max_length=10)),
                ('booked_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
