# Generated by Django 4.2 on 2023-04-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(choices=[('8 AM', '8 AM'), ('10 AM', '10 AM'), ('12 AM', '12 AM'), ('2 PM', '2 PM'), ('4 PM', '4 PM'), ('6 PM', '6 PM'), ('8 PM', '8 PM')], default='2 PM', max_length=10),
        ),
    ]
